### ISSUE TITLE
Only apply update if different from original

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres-migrator#28]
Apply same formatter to original and transform so we can diff cleanly.
Maybe even apply sorting xslt (sort all nodes and attributes) ? But we'll have a mismatch between what we diff and what we show to the user (don't want to show the sorted XML), so it might not be such a good idea.

**Comment by abulte** [comment]
@streino Can you write a simple transformation that changes _something_? It's for the tests, with this change ⬆, `noop` won't create or duplicate records.

**Comment by streino** [comment]
Will do! And I just remembered you have to explicitly call `etree.indent` to format the XML, `pretty_print` isn't enough.

**Comment by streino** [comment]
Ah maybe too. I was referring `etree.tostring(pretty_print=True)` which clearly isn't enough.

**Comment by streino** [comment]
Here you go: https://github.com/ecolabdata/ecospheres-migrator/pull/51
