### ISSUE TITLE
Handle record types other than record/template

### ISSUE THREAD

**Issue by streino** [ecolabdata/ecospheres-migrator#40]
OK to just ignore?

**Comment by abulte** [comment]
Should we introduce a SkippedRecord for this and #28? Or use the error one like for drafts with working copy.

**Comment by streino** [comment]
I like the idea of `SkippedRecord`, or we could refactor `FailedRecord` to have a error/skipped state. Either way, it's probably a good idea to be able to differentiate the two in reporting.

**Comment by abulte** [comment]
Let's go Skippy then 🦘

**Comment by streino** [comment]
Turns out `isTemplate` isn't a boolean: 
```
public enum MetadataType {
    METADATA('n'),
    TEMPLATE('y'),
    SUB_TEMPLATE('s'),
    TEMPLATE_OF_SUB_TEMPLATE('t');
```

🤷

**Comment by abulte** [comment]
Done #55
